import { Router, Request, Response } from "express";

export const modelsRouter = Router();

const MODEL_STACK = {
  _meta: "Arena LLM Stack — Juno Intelligence Core",
  _version: "2.0.0",
  _updated: new Date().toISOString().split("T")[0],
  primary_provider: "juno-core",
  fallback_chain: ["juno-core", "groq", "openrouter", "deepseek", "gemini", "kimi", "openai", "offline"],
  models: {
    translation: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.1,
      max_tokens: 512,
    },
    translation_prompt: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.1,
      max_tokens: 1000,
    },
    chat: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.72,
      max_tokens: 1024,
    },
    monitor: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.2,
      max_tokens: 400,
    },
    knowledge: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.3,
      max_tokens: 800,
    },
    general: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.5,
      max_tokens: 600,
    },
    background: {
      model: "llama-3.3-70b-versatile",
      provider: "juno-core",
      temperature: 0.4,
      max_tokens: 2048,
    },
  },
  provider_timeouts_ms: {
    "juno-core": 30000,
    groq: 10000,
    openrouter: 15000,
    gemini: 15000,
    claude: 25000,
    kimi: 15000,
    deepseek: 12000,
    openai: 20000,
  },
  rate_limits: {
    "juno-core": { dailyTokenBudget: 5000000 },
    groq: { dailyTokenBudget: 500000 },
    openrouter: { dailyTokenBudget: 500000 },
    gemini: { dailyTokenBudget: 100000 },
    claude: { dailyTokenBudget: 30000 },
    kimi: { dailyTokenBudget: 50000 },
    deepseek: { dailyTokenBudget: 150000 },
  },
  juno_persona: {
    name: "Juno",
    voice: "nova",
    personality: "warm, intelligent, conversational",
    greeting_prompts: [
      "What would you like to translate today?",
      "What language are you working with?",
      "Do you want to speak or type?",
      "You can talk about anything — I'll translate it for you.",
      "Are you translating something for a trip or a conversation?",
      "Say anything in your language and I'll handle the rest.",
      "Need to break a language barrier? Let's go.",
    ],
  },
  feature_flags: {
    conversational_ai: true,
    knowledge_context: true,
    voice_translation: true,
    tts_enabled: true,
    streaming_responses: false,
    arena_routing: true,
    image_generation: true,
  },
};

const MODEL_REGISTRY = {
  models: [
    {
      id: "juno-core-primary",
      name: "Juno Intelligence Core (Groq/OpenRouter/Anthropic)",
      provider: "juno-core",
      endpoint: process.env.JUNO_CORE_URL || "",
      model: "llama-3.3-70b-versatile",
      type: "chat",
      priority: -200,
      weight: 500,
      cost: 0,
      quality: 10,
      speed: 9,
      timeoutMs: 30000,
    },
    {
      id: "groq-llama33",
      name: "Llama 3.3 70B (Groq, Free Tier)",
      provider: "groq",
      endpoint: "https://api.groq.com/openai/v1",
      model: "llama-3.3-70b-versatile",
      type: "chat",
      priority: -9,
      weight: 200,
      cost: 0,
      quality: 9,
      speed: 10,
      timeoutMs: 10000,
    },
    {
      id: "openrouter-qwen3-30b",
      name: "Qwen3 30B (OpenRouter, Free)",
      provider: "openrouter",
      endpoint: "https://openrouter.ai/api/v1",
      model: "qwen/qwen3-30b-a3b:free",
      type: "chat",
      priority: -3,
      weight: 120,
      cost: 0,
      quality: 8,
      speed: 7,
      timeoutMs: 15000,
    },
    {
      id: "openrouter-gemma-27b",
      name: "Gemma 3 27B (OpenRouter, Free)",
      provider: "openrouter",
      endpoint: "https://openrouter.ai/api/v1",
      model: "google/gemma-3-27b-it:free",
      type: "chat",
      priority: -2,
      weight: 80,
      cost: 0,
      quality: 8,
      speed: 7,
      timeoutMs: 15000,
    },
    {
      id: "deepseek-v3-chat",
      name: "DeepSeek V3",
      provider: "deepseek",
      endpoint: "https://api.deepseek.com/v1",
      model: "deepseek-chat",
      type: "chat",
      priority: -4,
      weight: 100,
      cost: 0,
      quality: 9,
      speed: 6,
      dailyTokenBudget: 150000,
      timeoutMs: 15000,
    },
    {
      id: "pollinations-free",
      name: "Pollinations (Free, No Key)",
      provider: "pollinations",
      endpoint: "https://text.pollinations.ai",
      model: "openai",
      type: "chat",
      priority: -10,
      weight: 60,
      cost: 0,
      quality: 7,
      speed: 8,
      timeoutMs: 15000,
    },
    {
      id: "gemini-flash",
      name: "Gemini 2.0 Flash (Free Tier)",
      provider: "gemini",
      endpoint: "https://generativelanguage.googleapis.com",
      model: "gemini-2.0-flash",
      type: "chat",
      priority: -1,
      weight: 80,
      cost: 0,
      quality: 8,
      speed: 8,
      dailyTokenBudget: 100000,
      timeoutMs: 15000,
    },
    {
      id: "claude-3-haiku",
      name: "Claude 3.5 Haiku",
      provider: "claude",
      endpoint: "https://api.anthropic.com",
      model: "claude-3-5-haiku-20241022",
      type: "chat",
      priority: 5,
      weight: 50,
      cost: 1,
      quality: 9,
      speed: 8,
      dailyTokenBudget: 30000,
      timeoutMs: 25000,
    },
    {
      id: "libretranslate",
      name: "LibreTranslate (Free, Translation Only)",
      provider: "libretranslate",
      endpoint: "https://libretranslate.com",
      model: "libre",
      type: "translation",
      priority: 3,
      weight: 30,
      cost: 0,
      quality: 6,
      speed: 9,
      timeoutMs: 8000,
    },
    {
      id: "fallback-basic",
      name: "Offline Phrase Cache",
      provider: "offline",
      endpoint: "local",
      model: "phrase-cache",
      type: "fallback",
      priority: 99,
      weight: 10,
      cost: 0,
      quality: 4,
      speed: 10,
      timeoutMs: 100,
    },
  ],
};

modelsRouter.get("/models/stack", (_req: Request, res: Response) => {
  res.json(MODEL_STACK);
});

modelsRouter.get("/models/registry", (_req: Request, res: Response) => {
  res.json(MODEL_REGISTRY);
});

modelsRouter.get("/models/select", (req: Request, res: Response) => {
  const task = (req.query.task as string) || "chat";
  const taskConfig = MODEL_STACK.models[task as keyof typeof MODEL_STACK.models];
  if (!taskConfig) {
    return res.status(404).json({ error: `No model configured for task: ${task}` });
  }
  return res.json({
    task,
    model: taskConfig.model,
    provider: taskConfig.provider,
    temperature: taskConfig.temperature,
    max_tokens: taskConfig.max_tokens,
  });
});
